title: Be better Be growth Everyday 
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY
typewrite-text: Be better Be growth Everyday 

url: "https://kwon0202.github.io"
baseurl: "/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Catagory
    url: /catagory
  - title: Posts
    url: /posts
#  - title: Articles
#    url: /articles
social:
  github: kwon0202
#  twitter: brianmaierjr
#  facebook: brianmaierjr
  email: 
  #  linkedin: brianmaierjr
  
 <script src="https://utteranc.es/client.js"
        repo="kwon0202/blog-comments"
        issue-term="pathname"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>

repository               : "kwon0202/kwon0202.github.io" # GitHub username/repo-name e.g. ""

google_analytics: 

comments:
provider: "utterances"
utterances:
  theme: "github-light" # "github-dark"
  issue_term: "pathname"

