title: kyoungwon
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY
typewrite-text: Be better Be growth Everyday 

url: "https://kwon0202.github.io"
baseurl: "/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
# - title: Contact
#    url: /contact

social:
  github: brianmaierjr
#  twitter: brianmaierjr
#  facebook: brianmaierjr
  email: kyoungwon0202@gmail.com
#  linkedin: brianmaierjr

google_analytics: 

disqus:
    shortname: kwon0202
